package com.jsp.multiThreading;

public class Program3 {
	public static void main(String[] args) {
		for(int i = 0;i<5;i++) {
			Thread th = Thread.currentThread();
			System.out.println("Id: "+th.getId() + "| Name: " + th.getName() + "| Priority: " + th.getPriority());
		}
		System.out.println("Program Ends.........");
	}
}

//Output:

//Program Starts..........
//Main Thread.......
//Sample Thread.....
//Sample Thread.....
//Sample Thread.....
//Main Thread.......
//Main Thread.......
//Main Thread.......
//Main Thread.......
//Program Ends.........
//Sample Thread.....
//Sample Thread.....
//
