package com.jsp.multiThreading;

class DemoThread extends Thread{//Step 1
	@Override
	public void run() {//Step 2
		for(int i = 0;i<5;i++) {
			System.out.println("demo thread.....");
		}
	}
}

public class Program1 {
	public static void main(String[] args) {
		System.out.println("Program Starts..........");
		DemoThread dt = new DemoThread();//Step 3
		dt.start();//Step 4
		for(int i = 0;i<5;i++) {
			System.out.println("Main Thread.......");
		}
		System.out.println("Program Ends.........");
	}
}

//Output:

//Program Starts..........
//Main Thread.......
//Main Thread.......
//Main Thread.......
//demo thread.....
//demo thread.....
//demo thread.....
//demo thread.....
//demo thread.....
//Main Thread.......
//Main Thread.......
//Program Ends.........

